# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: "WeatherForecast",
      clean: true,
      devices: ["simulator iPhone 16 Pro"]
    )
  end

  desc "Example of a TestFlight upload lane"
  lane :release do
      sync_code_signing
      disable_automatic_code_signing(path: "WeatherForecast.xcodeproj")
      build_app
      enable_automatic_code_signing(path: "WeatherForecast.xcodeproj")
      upload_to_testflight
  end
end
